### ISSUE TITLE
[BUG] - stuck at hiyacfw

### ISSUE THREAD

**Issue by littletoadies** [YourKalamity/lazy-dsi-file-downloader#12]
**Describe the bug**
the downloader gets stuck at "hiyaCFW.7z downloaded".

**To Reproduce**

**Expected behavior**
to download files to the sd card

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
- Python version [if using Python]

**Additional context**

**Comment by littletoadies** [comment]
i also forgot to say i was following trying to update hiyacfw and twilight menu and install godmode9i since i heard about it today.

**Comment by littletoadies** [comment]
i don't want to exit out since that might corrupt the sd card

**Comment by littletoadies** [comment]
nvm i just safely ejected it

**Comment by YourKalamity** [comment]
Exiting shouldn't corrupt the SD card, can you copy and paste the message you got on the terminal?

**Comment by YourKalamity** [comment]
Stale
