### ISSUE TITLE
[BUG] - Unlaunch download is not a zip file

### ISSUE THREAD

**Issue by josephrooks** [YourKalamity/lazy-dsi-file-downloader#13]
**Describe the bug**
Unlaunch download or unzip fails

**To Reproduce**
1. Run Lazy DSi File Downloader
2. Tell it to include Unlaunch
3. When it reaches Unlaunch download, "Exception in thread Thread-2" ending in "zipfile.BadZipFile: File is not a zip file"

**Expected behavior**
Unlaunch download is successful and puts files onto SD card

**Screenshots**
![image](https://user-images.githubusercontent.com/1420959/121789597-40139680-cba5-11eb-8a63-9961850e0fdf.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by YourKalamity** [comment]
Seems to be working fine for me; could you try running it again?
The site hosting Unlaunch might've gone down when you tried to downoad it

**Comment by YourKalamity** [comment]
Switched to downloading the version stored on the Web Archive to prevent future issues
