### ISSUE TITLE
[BUG] - no application found to open the file after extraction

### ISSUE THREAD

**Issue by avichou** [YourKalamity/lazy-dsi-file-downloader#18]
impossbile to open it,no application found

downdload and extract on macOS,i can only read it usuing textedit but that is useless

should launch the app 

macOS 12.2 m1

**Comment by YourKalamity** [comment]
Try launching it with the Terminal app

**Comment by YourKalamity** [comment]
I believe this is caused by the `.` in the filename, should be fixed with 8db85d365a66dd53c3dcb1b5129b6b5d8419eda8
