### ISSUE TITLE
Chrome and Windows Virus Warning

### ISSUE THREAD

**Issue by ChocolateCheese9** [YourKalamity/lazy-dsi-file-downloader#6]
When I download the exe, both Chrome and Windows warn me that it's a malicious file. Why is this?

**Comment by YourKalamity** [comment]
This is a known issue with PyInstaller. As long as you are getting the exe from this GitHub, I can assure you there is no virus bundled with it.
Add an exception to your antivirus/ Windows Defender software.

**Comment by ChocolateCheese9** [comment]
Thank you. Just wanted to be safe. I’m kinda paranoid about that kind of stuff.
