### ISSUE TITLE
[BUG] - 7-zip not installed error

### ISSUE THREAD

**Issue by bland-user** [YourKalamity/lazy-dsi-file-downloader#8]
When I attempt to setup a SD card with the windows executable it says "7-Zip not found" even though I have 7-zip installed however it is not in the windows directory it is instead on my Desktop.

![image](https://user-images.githubusercontent.com/81486569/112731364-1c797200-8f0d-11eb-87a9-c262e92996c9.png)

I am unable to move 7-zip to the windows directory.

**Comment by YourKalamity** [comment]
Try reinstalling 7zip

**Comment by bland-user** [comment]
> 
> 
> Try reinstalling 7zip

Just did and it is still telling me that it cant find 7-zip

**Comment by YourKalamity** [comment]
Which version did you install and how?

**Comment by bland-user** [comment]
I installed: 7-Zip 19.00 (2019-02-21) for Windows
with: .exe | 64-bit x64 | 7-Zip for 64-bit Windows x64 (Intel 64 or AMD64)
(the second installer listed)
and installed it to my desktop again

**Comment by YourKalamity** [comment]
https://www.7-zip.org/a/7z1900.exe
Try installing this one (32-bit version) into the default directory

**Comment by bland-user** [comment]
> https://www.7-zip.org/a/7z1900.exe
> Try installing this one (32-bit version) into the default directory
I cannot right now but maybe later today or tomorrow

**Comment by bland-user** [comment]
![image](https://user-images.githubusercontent.com/81486569/112736700-05497d00-8f2b-11eb-8a18-e7a5ffccb56f.png)

**Comment by YourKalamity** [comment]
Right click and Run with administrator privileges

**Comment by bland-user** [comment]
> 
> 
> Right click and Run with administrator privileges

not an option.

**Comment by YourKalamity** [comment]
I am unsure why it is not running for you, try following the manual SD card setup steps instead on dsi.cfw.guide

**Comment by nezbite** [comment]
Access to files in the Program Files is usually restricted to non admin software. You either need to install 7zip as an admin or add an entry for 7zip in your registry linking to your 7za.exe file somewhere else, though I am not sure if you can edit your registry without admin privileges.
If you understand a bit of python you could change the code in the main.py to point to your 7za.exe directly and run the sourcecode directly.

**Comment by YourKalamity** [comment]
#11 
Switching to py7zr may solve the issues with locating executables and wouldn't require users to install 7-Zip beforehand.

**Comment by YourKalamity** [comment]
Fixed with a618d49288186ad942e9aaecf6d18eff68a3994a
