### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by qqq1701** [YourKalamity/lazy-dsi-file-downloader#9]
Windows automatically removing the file. Got it to virustotal and 7 scanners reported it was a virus.

**Comment by YourKalamity** [comment]
Unfortunately there is not much I can do right now to disable the false virus warning. This is an issue with PyInstaller and how Windows deals with unsigned code (to pressure developers to purchase signing certificates)
As long as you’re getting it from here, I can assure you the software contains no virus; you can also install Python on your system and run the python scripts manually.

Work is in progress to switch to Qt (and hopefully remove the virus warnings)
